trigger:
- main

pool:
  name: 'SelfHostedPool'  # Nome do seu Self-hosted Agent Pool

variables:
- group: 'DockerCredentials'  # Grupo com as variáveis DOCKER_USERNAME e DOCKER_PASSWORD

steps:
# Login no Docker Hub usando PowerShell
- powershell: |
    $dockerUser = "$(DOCKER_USERNAME)"
    $dockerToken = "$(DOCKER_PASSWORD)"
    $dockerToken | docker login -u $dockerUser --password-stdin
  displayName: 'Login no Docker Hub usando PowerShell'

# Build da Imagem Docker
- script: |
    docker build -t $(DOCKER_USERNAME)/unyleya_projeto:latest .
  displayName: 'Build da Imagem Docker'

# Push da Imagem Docker
- script: |
    docker push $(DOCKER_USERNAME)/unyleya_projeto:latest
  displayName: 'Push da Imagem para o Docker Hub'

# Listar Imagens para Validação
- script: |
    docker images
  displayName: 'Listar Imagens Locais'
