trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  name: SelfHostedPool

variables:
  DOCKER_REGISTRY: 'docker.io'
  DOCKER_REPOSITORY: 'flavioao/unyleya_projeto_cicd_flaviooliveira'
  DOCKER_IMAGE_TAG: 'latest'
  DOCKER_USERNAME: 'flavioao'
  DOCKER_PASSWORD: 'Jamile@2024'

steps:
- script: |
    echo "DOCKER_USERNAME: $(DOCKER_USERNAME)"
    echo "DOCKER_PASSWORD: $(DOCKER_PASSWORD)"
  displayName: 'Debug Variáveis'

# Login no Docker Hub
- script: |
   echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
   displayName: 'Login no Docker Hub'

# Build da imagem Docker
- script: |
    docker build -t $(DOCKER_REGISTRY)/$(DOCKER_REPOSITORY):$(DOCKER_IMAGE_TAG) .
  displayName: 'Build da imagem Docker'

# Push da imagem Docker
- script: |
    docker push $(DOCKER_REGISTRY)/$(DOCKER_REPOSITORY):$(DOCKER_IMAGE_TAG)
  displayName: 'Push da imagem Docker'
