trigger:
- main

pool:
  name: 'SelfHostedPool'  # Nome do seu Self-hosted Agent Pool

variables:
- group: 'DockerCredentials'  # Grupo com as variáveis DOCKER_USERNAME e DOCKER_PASSWORD

steps:
- powershell: |
    Write-Host "DOCKER_USERNAME: $(DOCKER_USERNAME)"
    Write-Host "DOCKER_PASSWORD length: $($(DOCKER_PASSWORD).Length)"
  displayName: 'Debug das Variáveis'

# Login no Docker Hub usando PowerShell
- powershell: |
    $dockerUser = "$(DOCKER_USERNAME)"
    $dockerToken = "$(DOCKER_PASSWORD)"

    if ($dockerUser -and $dockerToken) {
        $dockerToken | docker login -u $dockerUser --password-stdin
    } else {
        Write-Error "Variáveis DOCKER_USERNAME ou DOCKER_PASSWORD não estão definidas."
    }
  displayName: 'Login no Docker Hub usando PowerShell'
  env:
    DOCKER_USERNAME: $(DOCKER_USERNAME)
    DOCKER_PASSWORD: $(DOCKER_PASSWORD)

# Build da Imagem Docker
- script: |
    docker build -t $(DOCKER_USERNAME)/unyleya_projeto:latest .
  displayName: 'Build da Imagem Docker'

# Push da Imagem Docker
- script: |
    docker push $(DOCKER_USERNAME)/unyleya_projeto:latest
  displayName: 'Push da Imagem para o Docker Hub'

# Listar Imagens para Validação
- script: |
    docker images
  displayName: 'Listar Imagens Locais'
