# Gatilho para a branch principal
trigger:
- main

# Configuração do agente
pool:
  name: 'SelfHostedPool'  # Nome do seu agente self-hosted

# Referência ao grupo de variáveis seguro
variables:
- group: 'DockerCredentials'

steps:

# Debug das Variáveis
- script: |
    echo "DOCKER_USERNAME: $(DOCKER_USERNAME)"
    echo "DOCKER_PASSWORD length: ${#DOCKER_PASSWORD}"
  displayName: 'Debug das Variáveis'
  env:
    DOCKER_USERNAME: $(DOCKER_USERNAME)
    DOCKER_PASSWORD: $(DOCKER_PASSWORD)

# Login no Docker Hub
- script: |
    echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
  displayName: 'Login no Docker Hub'
  env:
    DOCKER_USERNAME: $(DOCKER_USERNAME)
    DOCKER_PASSWORD: $(DOCKER_PASSWORD)

# Build da Imagem Docker
- script: |
    docker build -t $(DOCKER_USERNAME)/unyleya_projeto:latest .
  displayName: 'Build da Imagem Docker'

# Push da Imagem para o Docker Hub
- script: |
    docker push $(DOCKER_USERNAME)/unyleya_projeto:latest
  displayName: 'Push da Imagem para o Docker Hub'

# Verificação Final
- script: |
    docker images
  displayName: 'Listar Imagens Docker Locais'
